### ISSUE TITLE
yarn "dev" doesn't compile *.hbs files

### ISSUE THREAD

**Issue by alitabatabaei** [statickidz/webpack-handlebars-bootstrap#1]
After running "yarn dev", changing the *.hbs files doesn't update the HTML outputs. I have to run "yarn build" and then "yarn dev" again to see the changes in HTMLs.

**Comment by statickidz** [comment]
#dfecf10

**Comment by statickidz** [comment]
dfecf10078cdd17983e31a3c552e2cb4cbf55da4
