### ISSUE TITLE
Dynjamic parameters in slug

### ISSUE THREAD

**Issue by kemalyen** [statickidz/webpack-handlebars-bootstrap#2]
Hi,

Is it possible to use dynamic parameters in routes:

I mean I wish to create custom slugs

http://localhost:3001/services/makeup.html
and bind them a route

/services/(:service)/.hbs

and render the content with an api

app/js will take the parameter and populate the list with parameter.

I do not want to use any frontend framework for only one two pages. I have written it on ReactJS but it's hard to implement the CSS codes.

Regards

**Comment by statickidz** [comment]
Hi @gazatem, unfortunately there isn't a workaround to get this but you can try to implement your own.
