### ISSUE TITLE
How to use handlebars template

### ISSUE THREAD

**Issue by david2vicente** [statickidz/webpack-handlebars-bootstrap#3]
Hello,

First of all, thank you for this nice starter kit ! 

I'm now trying to figure out to use handlebars template and import handlebars in app.js like in this basic example : https://codepen.io/SitePoint/pen/bdLRbE

Here is my code.

```
import $ from "jquery";
import 'bootstrap';
import './assets/styles/main.scss';
import Handlebars from 'handlebars/dist/handlebars.min';

$(document).ready(() => {
	var template = $('#handlebars-demo').html();

	var templateScript = Handlebars.compile(template);

	var context = {
		"name": "David James",
		"occupation": "developer"
	};

	var html = templateScript(context);
        $(document.body).append(html);
});
```
The html result : "My name is . I am a ."

Do i have something to modify in the webpack config to make this works ?

**Comment by statickidz** [comment]
Hi @david2vicente, this is not the main purporse of this starter kit but anyway I'll provide you a workaround to make this work.

What is happening it's that Handlebars it's trying to compile in execution time your vars to generate html and these came empty.

To scape variables and make this work you can scape your moustaches.

```html
<script id="handlebars-demo" type="text/x-handlebars-template">
	<div>
		My name is \{{name}}. I am a \{{occupation}}.	
	</div>
</script>
```

**Comment by david2vicente** [comment]
Perfect ! Thanks for the quick answer! 

When you say "not the main purpose", what do you mean ? 

I actually just want to use some fake data in a .json file to avoid duplicating stuff in html (like a list of users for example).

**Comment by statickidz** [comment]
I mean that this is made to serve static-precompiled site.

You can load that JSON data and using it to loop inside template but keep in mind that output will be static.
